### ISSUE TITLE
dave-selfservice-portal:  java.lang.IllegalArgumentException: clientRegistrationRepository ...

### ISSUE THREAD

**Issue by gislab-augsburg** [gislab-augsburg/helm-charts#8]
Error in dave-selfservice-portal pod:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' ...
... Caused by: java.lang.IllegalArgumentException: clientRegistrationRepository cannot be null
```

<details>

```

mb@nbo00370518:~/dave/helm-charts/charts/dave$ oc logs dave-selfservice-portal-65b4c794fb-mp7xr -f
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec -a "java" java -javaagent:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -XX:MaxRAMPercentage=80.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=200m -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/spring-boot-application.jar
INFO running in /deployments
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jolokia.util.ClassUtil (file:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar) to constructor sun.security.x509.X500Name(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.jolokia.util.ClassUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
I> No access restrictor found, access to any MBean is allowed
Jolokia: Agent started with URL https://10.138.43.136:8778/jolokia/
---------------------------------------------------------------------------------------------------------------------------------------------------
       _____                            __      __
      |  __ \              /\           \ \    / /
      | |  | |            /  \           \ \  / /    ___
      | |  | |           / /\ \           \ \/ /    / _ \
      | |__| |  _       / ____ \   _       \  /    |  __/  _
      |_____/  (_)     /_/    \_\ (_)       \/      \___| (_)
                                        _________________________
                     /\\      _____     |   |     |     |    | |  \
      ,-----,       /  \\____/__|__\_   |___|_____|_____|____|_|___\
   ,--'---:---`--, /  |  _     |     `| |                    | |    \
  ==(o)-----(o)==J    `(o)-------(o)=   --(o)(o)--------------(o)--'

 Datenbank und Auswertungen von Verkehrszählungen

 Application Name    : dave-selfserviceportal-apigateway
 Spring Boot Version :  (v2.7.8)
---------------------------------------------------------------------------------------------------------------------------------------------------
2024.02.29 13:08:26.094 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | ApiGatewayApplication | [StartupInfoLogger.java : 55] - Starting ApiGatewayApplication using Java 11.0.22 on dave-selfservice-portal-65b4c794fb-mp7xr with PID 1 (/deployments/spring-boot-application.jar started by 1003100000 in /deployments)
2024.02.29 13:08:26.097 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    DEBUG | [main] | ApiGatewayApplication | [StartupInfoLogger.java : 56] - Running with Spring Boot v2.7.8, Spring v5.3.25
2024.02.29 13:08:26.098 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | ApiGatewayApplication | [SpringApplication.java : 637] - The following 1 profile is active: "dev"
2024.02.29 13:08:36.308 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | GenericScope | [GenericScope.java : 283] - BeanFactory id=b4e03c3b-5f9a-3118-a443-b9c86cd39383
2024.02.29 13:08:42.286 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    WARN | [main] | HazelcastInstanceFactory | [StandardLoggerFactory.java : 56] - Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
2024.02.29 13:08:43.109 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | logo | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5]
        +       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
        + +   + +  |    |    / \       /  |      |     /         / \    |         |
        + + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |
        + +   + +  |    |  /     \   /    |      |     \       /     \       |    |
        +       +  o    o o       o o---o o----o o----o o---o o       o o----o    o
2024.02.29 13:08:43.109 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | system | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
2024.02.29 13:08:43.109 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | system | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] Hazelcast Platform 5.1.5 (20221114 - c52d6ff) starting at [10.138.43.136]:5701
2024.02.29 13:08:43.110 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | system | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] Cluster name: session_replication_group
2024.02.29 13:08:43.110 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | system | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed.
To enable integrity checker do one of the following:
  - Change member config using Java API: config.setIntegrityCheckerEnabled(true);
  - Change XML/YAML configuration property: Set hazelcast.integrity-checker.enabled to true
  - Add system property: -Dhz.integritychecker.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_INTEGRITYCHECKER_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2024.02.29 13:08:43.113 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | system | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2024.02.29 13:08:45.890 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | DiscoveryService | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] Kubernetes Discovery properties: { service-dns: null, service-dns-timeout: 5, service-name: apigateway, service-port: 0, service-label: null, service-label-value: true, namespace: dave-external, pod-label: null, pod-label-value: null, resolve-not-ready-addresses: true, expose-externally-mode: AUTO, use-node-name-as-external-address: false, service-per-pod-label: null, service-per-pod-label-value: null, kubernetes-api-retries: 3, kubernetes-master: https://kubernetes.default.svc}
2024.02.29 13:08:46.786 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | DiscoveryService | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] Kubernetes Discovery activated with mode: KUBERNETES_API
2024.02.29 13:08:46.788 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | security | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] Enable DEBUG/FINE log level for log category com.hazelcast.system.security  or use -Dhazelcast.security.recommendations system property to see �  security recommendations and the status of current config.
2024.02.29 13:08:47.220 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | Node | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] Using Discovery SPI
2024.02.29 13:08:47.283 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    WARN | [main] | CPSubsystem | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
2024.02.29 13:08:49.305 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | Diagnostics | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2024.02.29 13:08:49.384 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | LifecycleService | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] [10.138.43.136]:5701 is STARTING
2024.02.29 13:08:49.583 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | DiscoveryService | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] Cannot fetch the current zone, ZONE_AWARE feature is disabled
2024.02.29 13:08:49.602 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    WARN | [main] | DiscoveryService | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] Cannot fetch name of the node, NODE_AWARE feature is disabled
2024.02.29 13:08:49.697 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    WARN | [main] | KubernetesClient | [StandardLoggerFactory.java : 56] - Kubernetes API access is forbidden! Starting standalone. To use Hazelcast Kubernetes discovery, configure the required RBAC. For 'default' service account in 'default' namespace execute: `kubectl apply -f https://raw.githubusercontent.com/hazelcast/hazelcast/master/kubernetes-rbac.yaml`
2024.02.29 13:08:55.058 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | ClusterService | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5]

Members {size:1, ver:1} [
        Member [10.138.43.136]:5701 - 52ecf384-454f-4c6a-bc30-155973dd70d0 this
]

2024.02.29 13:08:55.085 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | LifecycleService | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] [10.138.43.136]:5701 is STARTED
2024.02.29 13:08:56.794 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | ReactiveUserDetailsServiceAutoConfiguration | [ReactiveUserDetailsServiceAutoConfiguration.java : 87] -

Using generated security password: 48f85bea-a62d-477c-a9ed-95c0884f267a

2024.02.29 13:08:58.092 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    WARN | [main] | AnnotationConfigReactiveWebServerApplicationContext | [AbstractApplicationContext.java : 591] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [de/muenchen/dave/configuration/SecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.web.server.SecurityWebFilterChain]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.IllegalArgumentException: clientRegistrationRepository cannot be null
2024.02.29 13:08:58.093 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | LifecycleService | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] [10.138.43.136]:5701 is SHUTTING_DOWN
2024.02.29 13:08:58.101 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | Node | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] Shutting down connection manager...
2024.02.29 13:08:58.190 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | Node | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] Shutting down node engine...
2024.02.29 13:08:58.290 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | NodeExtension | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] Destroying node NodeExtension.
2024.02.29 13:08:58.292 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | Node | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] Hazelcast Shutdown is completed in 194 ms.
2024.02.29 13:08:58.292 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | LifecycleService | [StandardLoggerFactory.java : 56] - [10.138.43.136]:5701 [session_replication_group] [5.1.5] [10.138.43.136]:5701 is SHUTDOWN
2024.02.29 13:08:58.304 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    WARN | [main] | DisposableBeanAdapter | [DisposableBeanAdapter.java : 222] - Invocation of destroy method failed on bean with name 'reactorServerResourceFactory': org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'braveTracer': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
2024.02.29 13:08:58.583 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    INFO | [main] | ConditionEvaluationReportLoggingListener | [ConditionEvaluationReportLoggingListener.java : 136] -

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024.02.29 13:08:58.792 | dave-selfserviceportal-apigateway | TraceId:  | SpanId: ] |
                    ERROR | [main] | SpringApplication | [SpringApplication.java : 821] - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [de/muenchen/dave/configuration/SecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.web.server.SecurityWebFilterChain]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.IllegalArgumentException: clientRegistrationRepository cannot be null
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
        at de.muenchen.dave.ApiGatewayApplication.main(ApiGatewayApplication.java:35)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.web.server.SecurityWebFilterChain]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.IllegalArgumentException: clientRegistrationRepository cannot be null
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
        ... 27 common frames omitted
Caused by: java.lang.IllegalArgumentException: clientRegistrationRepository cannot be null
        at org.springframework.util.Assert.notNull(Assert.java:201)
        at org.springframework.security.oauth2.client.web.server.DefaultServerOAuth2AuthorizationRequestResolver.<init>(DefaultServerOAuth2AuthorizationRequestResolver.java:120)
        at org.springframework.security.oauth2.client.web.server.DefaultServerOAuth2AuthorizationRequestResolver.<init>(DefaultServerOAuth2AuthorizationRequestResolver.java:105)
        at org.springframework.security.oauth2.client.web.server.OAuth2AuthorizationRequestRedirectWebFilter.<init>(OAuth2AuthorizationRequestRedirectWebFilter.java:93)
        at org.springframework.security.config.web.server.ServerHttpSecurity$OAuth2LoginSpec.getRedirectWebFilter(ServerHttpSecurity.java:3716)
        at org.springframework.security.config.web.server.ServerHttpSecurity$OAuth2LoginSpec.configure(ServerHttpSecurity.java:3581)
        at org.springframework.security.config.web.server.ServerHttpSecurity.build(ServerHttpSecurity.java:1437)
        at de.muenchen.dave.configuration.SecurityConfiguration.springSecurityFilterChain(SecurityConfiguration.java:79)
        at de.muenchen.dave.configuration.SecurityConfiguration$$EnhancerBySpringCGLIB$$3c5bd62a.CGLIB$springSecurityFilterChain$0(<generated>)
        at de.muenchen.dave.configuration.SecurityConfiguration$$EnhancerBySpringCGLIB$$3c5bd62a$$FastClassBySpringCGLIB$$71409e59.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at de.muenchen.dave.configuration.SecurityConfiguration$$EnhancerBySpringCGLIB$$3c5bd62a.springSecurityFilterChain(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 28 common frames omitted


```

</details>

@DanielOber Next One 😬

**Comment by gislab-augsburg** [comment]
Anderer Fehler nach #5
